# Generated by Django 3.2.21 on 2023-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('department', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('regno', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('volunteer_attendance', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'volunteer',
                'managed': False,
            },
        ),
    ]
