# Generated by Django 3.2.21 on 2023-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.CharField(max_length=45)),
                ('percentage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
    ]
