# Generated by Django 3.2.21 on 2023-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=45)),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('e_nature', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
